# Generated by Django 3.0.6 on 2020-06-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0004_peliculas1'),
    ]

    operations = [
        migrations.CreateModel(
            name='xxx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('edad', models.CharField(max_length=30)),
            ],
        ),
    ]
